CREATE TABLE [dbo].[Quote]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Quote] NVARCHAR(MAX) NOT NULL, 
    [Author] NVARCHAR(50) NOT NULL, 
    [Book] NVARCHAR(50) NOT NULL, 
    [Date Stamp] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
